#!/bin/bash
DB=$1
DBPATH=$2
WAREHOUSE="user/hive/warehouse/$DBPATH.db"

hive<<EOF
use $DB;
drop table tac_hour_http;
CREATE EXTERNAL TABLE tac_hour_http(
time                        string,
tac                         string,
browsedownloadvisits        int,
videoservicevisits          int,
instantmessagevisits        int,
appvisits                   int,
browsedownloadbusiness      int,
videoservicebusiness        int,
instantmessagebusiness      int,
appbusiness                 int,
dnsQuerySucc                int,
dnsQueryAtt                 int,
tcpSetupSucc                int,
tcpSetupReq                 int,
BearerULTCPRetransmit       int,
BearerULTCPTransmit         int,
BearerDLTCPRetransmit       int,
BearerDLTCPTransmit         int,
BearerULTCPMissequence      int,
BearerDLTCPMissequence      int,
pageresp                    int,
pagereq                     int,
pageresptimeall             int,
pageshowsucc                int,
pageshowtimeall             int,
httpdownflow                int,
httpdowntime                int,
mediasucc                   int,
mediareq                    int,
mediadownflow               double,
mediadowntime               int,
ServiceIMSucc               int,
ServiceIMReq                int,
readvisits                  int,
wbvisits                    int,
navigationvisits            int,
musicvisits                 int,
gamevisits                  int,
payvisits                   int,
Animevisits                 int,
mailvisits                  int,
p2pvisits                   int,
voipvisits                  int,
MultimediaMsgvisits         int,
financialvisits            int,
securityvisits              int,
shoppingvisits              int,
travelvisits                int,
cloudstoragevisits          int,
othervisits                 int,
readbusiness                int,
wbbusiness                  int,
navigationbusiness          int,
musicbusiness               int,
gamebusiness                int,
paybusiness                 int,
Animebusiness               int,
mailbusiness                int,
p2pbusiness                 int,
voipbusiness                int,
MultimediaMsgbusiness       int,
financialbusiness           int,
securitybusiness            int,
shoppingbusiness            int,
travelbusiness              int,
cloudstoragebusiness        int,
otherbusiness               int,
mediaRespTimeall            int,
mediaResp                   int,
ServiceIMTrans              int,
ServiceIMFlow               double,
ServiceIMTime               int
)PARTITIONED BY (
  dt string,
  h string)
ROW FORMAT DELIMITED
  FIELDS TERMINATED BY ','
LOCATION
  'hdfs://dtcluster/$WAREHOUSE/tac_hour_http';

drop table tac_day_http;
CREATE EXTERNAL TABLE tac_day_http(
time                        string,
tac                         string,
browsedownloadvisits        int,
videoservicevisits          int,
instantmessagevisits        int,
appvisits                   int,
browsedownloadbusiness      int,
videoservicebusiness        int,
instantmessagebusiness      int,
appbusiness                 int,
dnsQuerySucc                int,
dnsQueryAtt                 int,
tcpSetupSucc                int,
tcpSetupReq                 int,
BearerULTCPRetransmit       int,
BearerULTCPTransmit         int,
BearerDLTCPRetransmit       int,
BearerDLTCPTransmit         int,
BearerULTCPMissequence      int,
BearerDLTCPMissequence      int,
pageresp                    int,
pagereq                     int,
pageresptimeall             int,
pageshowsucc                int,
pageshowtimeall             int,
httpdownflow                int,
httpdowntime                int,
mediasucc                   int,
mediareq                    int,
mediadownflow               double,
mediadowntime               int,
ServiceIMSucc               int,
ServiceIMReq                int,
readvisits                  int,
wbvisits                    int,
navigationvisits            int,
musicvisits                 int,
gamevisits                  int,
payvisits                   int,
Animevisits                 int,
mailvisits                  int,
p2pvisits                   int,
voipvisits                  int,
MultimediaMsgvisits         int,
financialvisits            int,
securityvisits              int,
shoppingvisits              int,
travelvisits                int,
cloudstoragevisits          int,
othervisits                 int,
readbusiness                int,
wbbusiness                  int,
navigationbusiness          int,
musicbusiness               int,
gamebusiness                int,
paybusiness                 int,
Animebusiness               int,
mailbusiness                int,
p2pbusiness                 int,
voipbusiness                int,
MultimediaMsgbusiness       int,
financialbusiness           int,
securitybusiness            int,
shoppingbusiness            int,
travelbusiness              int,
cloudstoragebusiness        int,
otherbusiness               int,
mediaRespTimeall            int,
mediaResp                   int,
ServiceIMTrans              int,
ServiceIMFlow               double,
ServiceIMTime               int
)PARTITIONED BY (
  dt string)
ROW FORMAT DELIMITED
  FIELDS TERMINATED BY ','
LOCATION
  'hdfs://dtcluster/$WAREHOUSE/tac_day_http';

drop table cell_hour_http;
CREATE EXTERNAL TABLE cell_hour_http(
time                        string,
cellid                      bigint,
browsedownloadvisits        int,
videoservicevisits          int,
instantmessagevisits        int,
appvisits                   int,
browsedownloadbusiness      int,
videoservicebusiness        int,
instantmessagebusiness      int,
appbusiness                 int,
dnsQuerySucc                int,
dnsQueryAtt                 int,
tcpSetupSucc                int,
tcpSetupReq                 int,
BearerULTCPRetransmit       int,
BearerULTCPTransmit         int,
BearerDLTCPRetransmit       int,
BearerDLTCPTransmit         int,
BearerULTCPMissequence      int,
BearerDLTCPMissequence      int,
pageresp                    int,
pagereq                     int,
pageresptimeall             int,
pageshowsucc                int,
pageshowtimeall             int,
httpdownflow                int,
httpdowntime                int,
mediasucc                   int,
mediareq                    int,
mediadownflow               double,
mediadowntime               int,
ServiceIMSucc               int,
ServiceIMReq                int,
readvisits                  int,
wbvisits                    int,
navigationvisits            int,
musicvisits                 int,
gamevisits                  int,
payvisits                   int,
Animevisits                 int,
mailvisits                  int,
p2pvisits                   int,
voipvisits                  int,
MultimediaMsgvisits         int,
financialvisits            int,
securityvisits              int,
shoppingvisits              int,
travelvisits                int,
cloudstoragevisits          int,
othervisits                 int,
readbusiness                int,
wbbusiness                  int,
navigationbusiness          int,
musicbusiness               int,
gamebusiness                int,
paybusiness                 int,
Animebusiness               int,
mailbusiness                int,
p2pbusiness                 int,
voipbusiness                int,
MultimediaMsgbusiness       int,
financialbusiness           int,
securitybusiness            int,
shoppingbusiness            int,
travelbusiness              int,
cloudstoragebusiness        int,
otherbusiness               int,
mediaRespTimeall            int,
mediaResp                   int,
ServiceIMTrans              int,
ServiceIMFlow               double,
ServiceIMTime               int
)PARTITIONED BY (
  dt string,
  h string)
ROW FORMAT DELIMITED
  FIELDS TERMINATED BY ','
LOCATION
  'hdfs://dtcluster/$WAREHOUSE/cell_hour_http';

drop table cell_day_http;
CREATE EXTERNAL TABLE cell_day_http(
time                        string,
cellid                      bigint,
browsedownloadvisits        int,
videoservicevisits          int,
instantmessagevisits        int,
appvisits                   int,
browsedownloadbusiness      int,
videoservicebusiness        int,
instantmessagebusiness      int,
appbusiness                 int,
dnsQuerySucc                int,
dnsQueryAtt                 int,
tcpSetupSucc                int,
tcpSetupReq                 int,
BearerULTCPRetransmit       int,
BearerULTCPTransmit         int,
BearerDLTCPRetransmit       int,
BearerDLTCPTransmit         int,
BearerULTCPMissequence      int,
BearerDLTCPMissequence      int,
pageresp                    int,
pagereq                     int,
pageresptimeall             int,
pageshowsucc                int,
pageshowtimeall             int,
httpdownflow                int,
httpdowntime                int,
mediasucc                   int,
mediareq                    int,
mediadownflow               double,
mediadowntime               int,
ServiceIMSucc               int,
ServiceIMReq                int,
readvisits                  int,
wbvisits                    int,
navigationvisits            int,
musicvisits                 int,
gamevisits                  int,
payvisits                   int,
Animevisits                 int,
mailvisits                  int,
p2pvisits                   int,
voipvisits                  int,
MultimediaMsgvisits         int,
financialvisits            int,
securityvisits              int,
shoppingvisits              int,
travelvisits                int,
cloudstoragevisits          int,
othervisits                 int,
readbusiness                int,
wbbusiness                  int,
navigationbusiness          int,
musicbusiness               int,
gamebusiness                int,
paybusiness                 int,
Animebusiness               int,
mailbusiness                int,
p2pbusiness                 int,
voipbusiness                int,
MultimediaMsgbusiness       int,
financialbusiness           int,
securitybusiness            int,
shoppingbusiness            int,
travelbusiness              int,
cloudstoragebusiness        int,
otherbusiness               int,
mediaRespTimeall            int,
mediaResp                   int,
ServiceIMTrans              int,
ServiceIMFlow               double,
ServiceIMTime               int
)PARTITIONED BY (
  dt string)
ROW FORMAT DELIMITED
  FIELDS TERMINATED BY ','
LOCATION
  'hdfs://dtcluster/$WAREHOUSE/cell_day_http';


drop table sp_hour_http;
CREATE EXTERNAL TABLE sp_hour_http(
time                        string,
appserveripipv4             string,
browsedownloadvisits        int,
videoservicevisits          int,
instantmessagevisits        int,
appvisits                   int,
browsedownloadbusiness      int,
videoservicebusiness        int,
instantmessagebusiness      int,
appbusiness                 int,
dnsQuerySucc                int,
dnsQueryAtt                 int,
tcpSetupSucc                int,
tcpSetupReq                 int,
BearerULTCPRetransmit       int,
BearerULTCPTransmit         int,
BearerDLTCPRetransmit       int,
BearerDLTCPTransmit         int,
BearerULTCPMissequence      int,
BearerDLTCPMissequence      int,
pageresp                    int,
pagereq                     int,
pageresptimeall             int,
pageshowsucc                int,
pageshowtimeall             int,
httpdownflow                int,
httpdowntime                int,
mediasucc                   int,
mediareq                    int,
mediadownflow               double,
mediadowntime               int,
ServiceIMSucc               int,
ServiceIMReq                int,
readvisits                  int,
wbvisits                    int,
navigationvisits            int,
musicvisits                 int,
gamevisits                  int,
payvisits                   int,
Animevisits                 int,
mailvisits                  int,
p2pvisits                   int,
voipvisits                  int,
MultimediaMsgvisits         int,
financialvisits            int,
securityvisits              int,
shoppingvisits              int,
travelvisits                int,
cloudstoragevisits          int,
othervisits                 int,
readbusiness                int,
wbbusiness                  int,
navigationbusiness          int,
musicbusiness               int,
gamebusiness                int,
paybusiness                 int,
Animebusiness               int,
mailbusiness                int,
p2pbusiness                 int,
voipbusiness                int,
MultimediaMsgbusiness       int,
financialbusiness           int,
securitybusiness            int,
shoppingbusiness            int,
travelbusiness              int,
cloudstoragebusiness        int,
otherbusiness               int,
mediaRespTimeall            int,
mediaResp                   int,
ServiceIMTrans              int,
ServiceIMFlow               double,
ServiceIMTime               int
)PARTITIONED BY (
  dt string,
  h string)
ROW FORMAT DELIMITED
  FIELDS TERMINATED BY ','
LOCATION
  'hdfs://dtcluster/$WAREHOUSE/sp_hour_http';

drop table sp_day_http;
CREATE EXTERNAL TABLE sp_day_http(
time                        string,
appserveripipv4             string,
browsedownloadvisits        int,
videoservicevisits          int,
instantmessagevisits        int,
appvisits                   int,
browsedownloadbusiness      int,
videoservicebusiness        int,
instantmessagebusiness      int,
appbusiness                 int,
dnsQuerySucc                int,
dnsQueryAtt                 int,
tcpSetupSucc                int,
tcpSetupReq                 int,
BearerULTCPRetransmit       int,
BearerULTCPTransmit         int,
BearerDLTCPRetransmit       int,
BearerDLTCPTransmit         int,
BearerULTCPMissequence      int,
BearerDLTCPMissequence      int,
pageresp                    int,
pagereq                     int,
pageresptimeall             int,
pageshowsucc                int,
pageshowtimeall             int,
httpdownflow                int,
httpdowntime                int,
mediasucc                   int,
mediareq                    int,
mediadownflow               double,
mediadowntime               int,
ServiceIMSucc               int,
ServiceIMReq                int,
readvisits                  int,
wbvisits                    int,
navigationvisits            int,
musicvisits                 int,
gamevisits                  int,
payvisits                   int,
Animevisits                 int,
mailvisits                  int,
p2pvisits                   int,
voipvisits                  int,
MultimediaMsgvisits         int,
financialvisits            int,
securityvisits              int,
shoppingvisits              int,
travelvisits                int,
cloudstoragevisits          int,
othervisits                 int,
readbusiness                int,
wbbusiness                  int,
navigationbusiness          int,
musicbusiness               int,
gamebusiness                int,
paybusiness                 int,
Animebusiness               int,
mailbusiness                int,
p2pbusiness                 int,
voipbusiness                int,
MultimediaMsgbusiness       int,
financialbusiness           int,
securitybusiness            int,
shoppingbusiness            int,
travelbusiness              int,
cloudstoragebusiness        int,
otherbusiness               int,
mediaRespTimeall            int,
mediaResp                   int,
ServiceIMTrans              int,
ServiceIMFlow               double,
ServiceIMTime               int
)PARTITIONED BY (
  dt string)
ROW FORMAT DELIMITED
  FIELDS TERMINATED BY ','
LOCATION
  'hdfs://dtcluster/$WAREHOUSE/sp_day_http';


drop table ue_hour_http;
CREATE EXTERNAL TABLE ue_hour_http(
time                        string,
imsi                        string,
msisdn                      string,
browsedownloadvisits        int,
videoservicevisits          int,
instantmessagevisits        int,
appvisits                   int,
browsedownloadbusiness      int,
videoservicebusiness        int,
instantmessagebusiness      int,
appbusiness                 int,
dnsQuerySucc                int,
dnsQueryAtt                 int,
tcpSetupSucc                int,
tcpSetupReq                 int,
BearerULTCPRetransmit       int,
BearerULTCPTransmit         int,
BearerDLTCPRetransmit       int,
BearerDLTCPTransmit         int,
BearerULTCPMissequence      int,
BearerDLTCPMissequence      int,
pageresp                    int,
pagereq                     int,
pageresptimeall             int,
pageshowsucc                int,
pageshowtimeall             int,
httpdownflow                int,
httpdowntime                int,
mediasucc                   int,
mediareq                    int,
mediadownflow               double,
mediadowntime               int,
ServiceIMSucc               int,
ServiceIMReq                int,
readvisits                  int,
wbvisits                    int,
navigationvisits            int,
musicvisits                 int,
gamevisits                  int,
payvisits                   int,
Animevisits                 int,
mailvisits                  int,
p2pvisits                   int,
voipvisits                  int,
MultimediaMsgvisits         int,
financialvisits            int,
securityvisits              int,
shoppingvisits              int,
travelvisits                int,
cloudstoragevisits          int,
othervisits                 int,
readbusiness                int,
wbbusiness                  int,
navigationbusiness          int,
musicbusiness               int,
gamebusiness                int,
paybusiness                 int,
Animebusiness               int,
mailbusiness                int,
p2pbusiness                 int,
voipbusiness                int,
MultimediaMsgbusiness       int,
financialbusiness           int,
securitybusiness            int,
shoppingbusiness            int,
travelbusiness              int,
cloudstoragebusiness        int,
otherbusiness               int,
mediaRespTimeall            int,
mediaResp                   int,
ServiceIMTrans              int,
ServiceIMFlow               double,
ServiceIMTime               int
)PARTITIONED BY (
  dt string,
  h string)
ROW FORMAT DELIMITED
  FIELDS TERMINATED BY ','
LOCATION
  'hdfs://dtcluster/$WAREHOUSE/ue_hour_http';


drop table ue_day_http;
CREATE EXTERNAL TABLE ue_day_http(
time                        string,
imsi                        string,
msisdn                      string,
browsedownloadvisits        int,
videoservicevisits          int,
instantmessagevisits        int,
appvisits                   int,
browsedownloadbusiness      int,
videoservicebusiness        int,
instantmessagebusiness      int,
appbusiness                 int,
dnsQuerySucc                int,
dnsQueryAtt                 int,
tcpSetupSucc                int,
tcpSetupReq                 int,
BearerULTCPRetransmit       int,
BearerULTCPTransmit         int,
BearerDLTCPRetransmit       int,
BearerDLTCPTransmit         int,
BearerULTCPMissequence      int,
BearerDLTCPMissequence      int,
pageresp                    int,
pagereq                     int,
pageresptimeall             int,
pageshowsucc                int,
pageshowtimeall             int,
httpdownflow                int,
httpdowntime                int,
mediasucc                   int,
mediareq                    int,
mediadownflow               double,
mediadowntime               int,
ServiceIMSucc               int,
ServiceIMReq                int,
readvisits                  int,
wbvisits                    int,
navigationvisits            int,
musicvisits                 int,
gamevisits                  int,
payvisits                   int,
Animevisits                 int,
mailvisits                  int,
p2pvisits                   int,
voipvisits                  int,
MultimediaMsgvisits         int,
financialvisits            int,
securityvisits              int,
shoppingvisits              int,
travelvisits                int,
cloudstoragevisits          int,
othervisits                 int,
readbusiness                int,
wbbusiness                  int,
navigationbusiness          int,
musicbusiness               int,
gamebusiness                int,
paybusiness                 int,
Animebusiness               int,
mailbusiness                int,
p2pbusiness                 int,
voipbusiness                int,
MultimediaMsgbusiness       int,
financialbusiness           int,
securitybusiness            int,
shoppingbusiness            int,
travelbusiness              int,
cloudstoragebusiness        int,
otherbusiness               int,
mediaRespTimeall            int,
mediaResp                   int,
ServiceIMTrans              int,
ServiceIMFlow               double,
ServiceIMTime               int
)PARTITIONED BY (
  dt string)
ROW FORMAT DELIMITED
  FIELDS TERMINATED BY ','
LOCATION
  'hdfs://dtcluster/$WAREHOUSE/ue_day_http';

drop table imsi_cell_hour_http;
CREATE EXTERNAL TABLE imsi_cell_hour_http(
time                        string,
imsi                        string,
msisdn                      string,
cellid                      bigint,
browsedownloadvisits        int,
videoservicevisits          int,
instantmessagevisits        int,
appvisits                   int,
browsedownloadbusiness      int,
videoservicebusiness        int,
instantmessagebusiness      int,
appbusiness                 int,
dnsQuerySucc                int,
dnsQueryAtt                 int,
tcpSetupSucc                int,
tcpSetupReq                 int,
BearerULTCPRetransmit       int,
BearerULTCPTransmit         int,
BearerDLTCPRetransmit       int,
BearerDLTCPTransmit         int,
BearerULTCPMissequence      int,
BearerDLTCPMissequence      int,
pageresp                    int,
pagereq                     int,
pageresptimeall             int,
pageshowsucc                int,
pageshowtimeall             int,
httpdownflow                int,
httpdowntime                int,
mediasucc                   int,
mediareq                    int,
mediadownflow               double,
mediadowntime               int,
ServiceIMSucc               int,
ServiceIMReq                int,
readvisits                  int,
wbvisits                    int,
navigationvisits            int,
musicvisits                 int,
gamevisits                  int,
payvisits                   int,
Animevisits                 int,
mailvisits                  int,
p2pvisits                   int,
voipvisits                  int,
MultimediaMsgvisits         int,
financialvisits            int,
securityvisits              int,
shoppingvisits              int,
travelvisits                int,
cloudstoragevisits          int,
othervisits                 int,
readbusiness                int,
wbbusiness                  int,
navigationbusiness          int,
musicbusiness               int,
gamebusiness                int,
paybusiness                 int,
Animebusiness               int,
mailbusiness                int,
p2pbusiness                 int,
voipbusiness                int,
MultimediaMsgbusiness       int,
financialbusiness           int,
securitybusiness            int,
shoppingbusiness            int,
travelbusiness              int,
cloudstoragebusiness        int,
otherbusiness               int,
mediaRespTimeall            int,
mediaResp                   int,
ServiceIMTrans              int,
ServiceIMFlow               double,
ServiceIMTime               int
)PARTITIONED BY (
  dt string,
  h string)
ROW FORMAT DELIMITED
  FIELDS TERMINATED BY ','
LOCATION
  'hdfs://dtcluster/$WAREHOUSE/imsi_cell_hour_http';

drop table imsi_cell_day_http;
CREATE EXTERNAL TABLE imsi_cell_day_http(
time                        string,
imsi                        string,
msisdn                      string,
cellid                      bigint,
browsedownloadvisits        int,
videoservicevisits          int,
instantmessagevisits        int,
appvisits                   int,
browsedownloadbusiness      int,
videoservicebusiness        int,
instantmessagebusiness      int,
appbusiness                 int,
dnsQuerySucc                int,
dnsQueryAtt                 int,
tcpSetupSucc                int,
tcpSetupReq                 int,
BearerULTCPRetransmit       int,
BearerULTCPTransmit         int,
BearerDLTCPRetransmit       int,
BearerDLTCPTransmit         int,
BearerULTCPMissequence      int,
BearerDLTCPMissequence      int,
pageresp                    int,
pagereq                     int,
pageresptimeall             int,
pageshowsucc                int,
pageshowtimeall             int,
httpdownflow                int,
httpdowntime                int,
mediasucc                   int,
mediareq                    int,
mediadownflow               double,
mediadowntime               int,
ServiceIMSucc               int,
ServiceIMReq                int,
readvisits                  int,
wbvisits                    int,
navigationvisits            int,
musicvisits                 int,
gamevisits                  int,
payvisits                   int,
Animevisits                 int,
mailvisits                  int,
p2pvisits                   int,
voipvisits                  int,
MultimediaMsgvisits         int,
financialvisits            int,
securityvisits              int,
shoppingvisits              int,
travelvisits                int,
cloudstoragevisits          int,
othervisits                 int,
readbusiness                int,
wbbusiness                  int,
navigationbusiness          int,
musicbusiness               int,
gamebusiness                int,
paybusiness                 int,
Animebusiness               int,
mailbusiness                int,
p2pbusiness                 int,
voipbusiness                int,
MultimediaMsgbusiness       int,
financialbusiness           int,
securitybusiness            int,
shoppingbusiness            int,
travelbusiness              int,
cloudstoragebusiness        int,
otherbusiness               int,
mediaRespTimeall            int,
mediaResp                   int,
ServiceIMTrans              int,
ServiceIMFlow               double,
ServiceIMTime               int
)PARTITIONED BY (
  dt string)
ROW FORMAT DELIMITED
  FIELDS TERMINATED BY ','
LOCATION
  'hdfs://dtcluster/$WAREHOUSE/imsi_cell_day_http';

drop table sgw_hour_http;
CREATE EXTERNAL TABLE sgw_hour_http(
time                        string,
sgwipaddr                   string,
browsedownloadvisits        int,
videoservicevisits          int,
instantmessagevisits        int,
appvisits                   int,
browsedownloadbusiness      int,
videoservicebusiness        int,
instantmessagebusiness      int,
appbusiness                 int,
dnsQuerySucc                int,
dnsQueryAtt                 int,
tcpSetupSucc                int,
tcpSetupReq                 int,
BearerULTCPRetransmit       int,
BearerULTCPTransmit         int,
BearerDLTCPRetransmit       int,
BearerDLTCPTransmit         int,
BearerULTCPMissequence      int,
BearerDLTCPMissequence      int,
pageresp                    int,
pagereq                     int,
pageresptimeall             int,
pageshowsucc                int,
pageshowtimeall             int,
httpdownflow                int,
httpdowntime                int,
mediasucc                   int,
mediareq                    int,
mediadownflow               double,
mediadowntime               int,
ServiceIMSucc               int,
ServiceIMReq                int,
readvisits                  int,
wbvisits                    int,
navigationvisits            int,
musicvisits                 int,
gamevisits                  int,
payvisits                   int,
Animevisits                 int,
mailvisits                  int,
p2pvisits                   int,
voipvisits                  int,
MultimediaMsgvisits         int,
financialvisits            int,
securityvisits              int,
shoppingvisits              int,
travelvisits                int,
cloudstoragevisits          int,
othervisits                 int,
readbusiness                int,
wbbusiness                  int,
navigationbusiness          int,
musicbusiness               int,
gamebusiness                int,
paybusiness                 int,
Animebusiness               int,
mailbusiness                int,
p2pbusiness                 int,
voipbusiness                int,
MultimediaMsgbusiness       int,
financialbusiness           int,
securitybusiness            int,
shoppingbusiness            int,
travelbusiness              int,
cloudstoragebusiness        int,
otherbusiness               int,
mediaRespTimeall            int,
mediaResp                   int,
ServiceIMTrans              int,
ServiceIMFlow               double,
ServiceIMTime               int
)PARTITIONED BY (
  dt string,
  h string)
ROW FORMAT DELIMITED
  FIELDS TERMINATED BY ','
LOCATION
  'hdfs://dtcluster/$WAREHOUSE/sgw_hour_http';

drop table sgw_day_http;
CREATE EXTERNAL TABLE sgw_day_http(
time                        string,
sgwipaddr                   string,
browsedownloadvisits        int,
videoservicevisits          int,
instantmessagevisits        int,
appvisits                   int,
browsedownloadbusiness      int,
videoservicebusiness        int,
instantmessagebusiness      int,
appbusiness                 int,
dnsQuerySucc                int,
dnsQueryAtt                 int,
tcpSetupSucc                int,
tcpSetupReq                 int,
BearerULTCPRetransmit       int,
BearerULTCPTransmit         int,
BearerDLTCPRetransmit       int,
BearerDLTCPTransmit         int,
BearerULTCPMissequence      int,
BearerDLTCPMissequence      int,
pageresp                    int,
pagereq                     int,
pageresptimeall             int,
pageshowsucc                int,
pageshowtimeall             int,
httpdownflow                int,
httpdowntime                int,
mediasucc                   int,
mediareq                    int,
mediadownflow               double,
mediadowntime               int,
ServiceIMSucc               int,
ServiceIMReq                int,
readvisits                  int,
wbvisits                    int,
navigationvisits            int,
musicvisits                 int,
gamevisits                  int,
payvisits                   int,
Animevisits                 int,
mailvisits                  int,
p2pvisits                   int,
voipvisits                  int,
MultimediaMsgvisits         int,
financialvisits            int,
securityvisits              int,
shoppingvisits              int,
travelvisits                int,
cloudstoragevisits          int,
othervisits                 int,
readbusiness                int,
wbbusiness                  int,
navigationbusiness          int,
musicbusiness               int,
gamebusiness                int,
paybusiness                 int,
Animebusiness               int,
mailbusiness                int,
p2pbusiness                 int,
voipbusiness                int,
MultimediaMsgbusiness       int,
financialbusiness           int,
securitybusiness            int,
shoppingbusiness            int,
travelbusiness              int,
cloudstoragebusiness        int,
otherbusiness               int,
mediaRespTimeall            int,
mediaResp                   int,
ServiceIMTrans              int,
ServiceIMFlow               double,
ServiceIMTime               int
)PARTITIONED BY (
  dt string)
ROW FORMAT DELIMITED
  FIELDS TERMINATED BY ','
LOCATION
  'hdfs://dtcluster/$WAREHOUSE/sgw_day_http';

drop table warnningtable;
CREATE EXTERNAL TABLE warnningtable(
City  int,
Cellid   bigint,
warnningtitle    string,
warnningtime     string,
effect           string
)PARTITIONED BY (
  dt string,
  h string)
ROW FORMAT DELIMITED
  FIELDS TERMINATED BY ','
LOCATION
  'hdfs://dtcluster/$WAREHOUSE/warnningtable';

drop table t_xdr_event_msg;
CREATE EXTERNAL TABLE t_xdr_event_msg(
City   int,
XDRID  string,
ProcedureStartTime bigint,
ttime string,
ProcedureEndTime  bigint,
IMSI             string,
TAC              bigint,
Cellid           bigint,
SGW             string,
SP              string,
AppType         int,
AppSubtype      int,
AppStatus       int,
exceptiontype   string,
failurecase     string,
errorbelong     string
)PARTITIONED BY (
  dt string,
  h string)
ROW FORMAT DELIMITED
  FIELDS TERMINATED BY ','
LOCATION
  'hdfs://dtcluster/$WAREHOUSE/t_xdr_event_msg';


drop table LTECELL;
create table LTECELL(
  MCC         int,
  MNC         INT,
  MMEGROUPID  INT,
  MMEID       int,
  ENODEBID    int,
  SITENAME    STRING,
  CELLNAME    STRING,
  LOCALCELLID int,
  CELLID      int,
  TAI         INT,
  PCI         INT,
  FREQ1       INT,
  FREQ2       INT,
  BANDWIDTH1  double,
  BANDWIDTH2  double,
  FREQCOUNT   INT,
  LONGITUDE   double,
  LATITUDE    double,
  SECTORTYPE  int,
  DOORTYPE    INT,
  TILTTOTAL   DOUBLE,
  TILTM       DOUBLE,
  TILTE       DOUBLE,
  AZIMUTH     DOUBLE,
  BEAMWIDTH   DOUBLE,
  VBEAMWIDTH  DOUBLE,
  AHEIGHT     DOUBLE,
  CITY        string,
  COMPANY     string,
  REGION      string,
  ENBTYPE     string,
  ENBVERSION  string
  )ROW FORMAT DELIMITED
  FIELDS TERMINATED BY ',';

drop table business_type_detail;
create EXTERNAL table business_type_detail(
        TTIME              string,
        city               string,
        region             string,
        CELLID             int,
        app_type           string,
        app_sub_type       string,
        uldata             bigint,
        dldata             bigint
)
PARTITIONED BY (
  dt string,
  h string)
ROW FORMAT DELIMITED
  FIELDS TERMINATED BY ','
LOCATION
  'hdfs://dtcluster/$WAREHOUSE/business_type_detail';
EOF
